name: Create release in tracker
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Create ticket
        run: sh ./.github/scripts/add-release-yt.sh
        env:
          OAuth: ${{ secrets.YCAUTH }}
          OrganizationId: ${{ secrets.YCID }}
