name: Create release in tracker

on: [push]
jobs:
  create-ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Create ticket
        run: sh ./scripts/add-release-yt.sh
        env:
          OAuth: ${{ secrets.YCAUTH }}
          OrganizationId: ${{ secrets.YCID }}
