name: Create release in tracker

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Create ticket
        run: sh ./scripts/add-release-yt.sh
        env:
          OAuth: ${{ secrets.OAuth }}
          OrganizationId: ${{ secrets.OrganizationId }}

      - name: Install packages
        run: npm install

      - name: Run tests
        run: sh ./scripts/runtest.sh
        env:
          OAuth: ${{ secrets.OAuth }}
          OrganizationId: ${{ secrets.OrganizationId }}
